### ISSUE TITLE
Lua Client

### ISSUE THREAD

**Issue by dannysmc95** [legospacy/lua-irc-engine#10]
I was wondering do you have an example that adds to ability to send messages to the IRC server? While still receiving them and viewing them? Maybe a callback method? But I can't seem to figure out how to make this? Help would be appreciated.

Cheers

**Comment by legospacy** [comment]
I'm not quite sure what you mean. Say you have:
```lua
local IRCe = require("irce")
local irc = IRCe.new()
```
You can send raw IRC messages with `irc:send_raw(msg)`, eg. `irc:send_raw("PRIVMSG #test :Hello!")`, and send specific message types with a nicer interface, eg. `irc:send("PRIVMSG", "#test", "Hello!")`.

When you set callbacks for a message type eg. `irc:set_callback("PRIVMSG", function(self, sender, origin, msg, pm) print(sender[1] .. " said " .. msg) end)`, they get called if a message of that type is received through `irc:process(raw_msg)` (where `raw_msg` is a raw message received from the server).

Not sure if that covers what you need.

**Comment by legospacy** [comment]
Have you had a look at `example.lua`?

**Comment by dannysmc95** [comment]
Hello,

I have used example.lua, but I can't send input to the IRC channel from the command line? This is what I am asking? How would I do this? While still probing the server for the current chat data?

**Comment by legospacy** [comment]
Ah, I understand now. To be honest, I'm not sure you can do that just with standard Lua, since `file:read()/io.read()` is a blocking operation. There's probably libraries out there that let you do non-blocking reads, but I don't know any.

Sorry I can't be of more help.

**Comment by dannysmc95** [comment]
Hmm I guess, it may be possible with coroutines and a custom coroutine manager? Maybe run the main IRC code inside a coroutine, and put a custom read function to take character input? Instead, so when you press a key it writes it, it does not block any other code.

Do not worry, I did wonder whether it may be possible, I may experiment and see if I can convert what you have here to work with a simple IRC client, if you want and I can get it working, shall I make a pull request with a example_client.lua file?

**Comment by legospacy** [comment]
If you can get it to work without any other external libraries, that'd be nice!

**Comment by dannysmc95** [comment]
I will sure have a go!
