### ISSUE TITLE
IRCv3 tags not being sent to :handle()

### ISSUE THREAD

**Issue by ChickenNuggers** [legospacy/lua-irc-engine#12]
Is this doable by just changing two lines or would it require a larger refactoring? Currently the tags are parsed but not ever used.

**Comment by legospacy** [comment]
Yeah, you can just change two lines in :process() to have the tags passed to all handlers. I'm not familiar with what the tags are actually used for though; would this be enough, or should the tags also be passed unconditionally to callbacks?

**Comment by ChickenNuggers** [comment]
Tags get passed to the handler; for example, if - in the future, this isn't possible now - you were to support IRCv3's `server-time` tag, you could detect exactly what time a message was received by the server. There's not a large amount of tags implemented yet.

**Comment by legospacy** [comment]
With `server-time`, wouldn't the application want to know what the time was, regardless of what kind of message it was and thus which handler was called? I was under the impression that tags are generally message-type-independent.

In any case, that'll require some work, so for now I'll just have tags passed to handlers.

**Comment by ChickenNuggers** [comment]
They are, sorry for not clarifying; I just wanted to have an issue instead of a PR because I didn't know how you wanted to implement. Yes, they are independent of handlers.

**Comment by ChickenNuggers** [comment]
edb73ca49b6a225eb56394084ec33838a9c9b30f is the way my bot does it fwiw

**Comment by legospacy** [comment]
Ah, okay! This'll do for now, I'll see what I come up with later, probably when I research and implement `CAP`.
