### ISSUE TITLE
What to do on send func failure?

### ISSUE THREAD

**Issue by daurnimator** [legospacy/lua-irc-engine#3]
What should a `send_func` do if it encounters an error?
What about a timeout?

**Comment by legospacy** [comment]
Thanks for bringing this to my attention, I failed to consider it while I was writing the module.

`irc.send` returns everything returned by `irc.send_raw`, which in turn returns everything returned by the `send_func`; so my suggestion would be for the `send_func` to return `true` on success and `nil` or `false` plus an error message on failure, so the error can be caught by checking the return values of `irc.send` or `irc.send_raw`.

I'll add this information to the README, if you have no objections.

I don't get what you mean by "What about a timeout?", could you clarify?

**Comment by daurnimator** [comment]
> I don't get what you mean by "What about a timeout?", could you clarify?

How should a write timeout be handled? like any other error? or should it be treated specially (e.g. try again later)

**Comment by legospacy** [comment]
I feel that it should be reported like any other error. With this module, I'm going for a relatively thin layer between the host program and the networking, and so I think that it should be up to that host to handle all errors; in the case of a write timeout, maybe by wrapping `irc.send` to catch a signal from the `send_func` telling it to try sending again.
