### ISSUE TITLE
Invert module loading control

### ISSUE THREAD

**Issue by daurnimator** [legospacy/lua-irc-engine#4]
Rather than a ':load_module()' method that loads a file; it would be preferable that it takes a table in the module format. e.g. 
```lua
irc:load_module {
    handlers = {
        <command> = <func>
    }
}
```
This is far more flexible than requiring a directory layout.

**Comment by legospacy** [comment]
The only problem I forsee is that it wouldn't be feasible to implement unloading modules. I guess that's not too much of a problem though.

This is a great idea, thanks!

**Comment by daurnimator** [comment]
why couldn't unloading be implemented? ==> just pass the same table to unload?

**Comment by legospacy** [comment]
That could work, as long as you kept a reference to that table.

Ah, passing package.loaded[module_name] would work, didn't think of that.

**Comment by daurnimator** [comment]
> Ah, passing package.loaded[module_name] would work, didn't think of that.

assuming you only have only one irc module per lua module.

I'm imagining you might want to e.g. have more than one per file

**Comment by legospacy** [comment]
Okay, that should do it.
