### ISSUE TITLE
Create rockspec

### ISSUE THREAD

**Issue by daurnimator** [legospacy/lua-irc-engine#5]
Please create a luarocks rockspec.

As part of this, consider installing the default modules under an `irce` prefix.
e.g. `irce.modules.base`

**Comment by legospacy** [comment]
I've never made a Rockspec, so I'm going to do some research.

**Comment by daurnimator** [comment]
This one should end up pretty simple. You might want to look just work from one of mine.
e.g. https://rocks.moonscript.org/manifests/daurnimator/luatz-scm-0.rockspec or https://rocks.moonscript.org/manifests/daurnimator/lpeg_patterns-scm-0.rockspec

When using the 'builtin' build type, the `modules` table maps from the `require` string to where the file is located in your repo.

**Comment by legospacy** [comment]
Alright, done.

**Comment by daurnimator** [comment]
Don't forget to upload a `.src.rock` to moonrocks.
```
luarocks upload irc-engine-1.1.0-1.rockspec
```

And even (in your case) a `.all.rock`:

```
luarocks install irc-engine 1.1.0
luarocks pack irc-engine 1.1.0
luarocks upload irc-engine 1.1.0-1.all.rock
```

**Comment by legospacy** [comment]
I've got a `.src.rock` up, can't figure out `.all.rock`s. I'm too tired right now, I'll figure it out later.

**Comment by daurnimator** [comment]
> can't figure out .all.rocks. I'm too tired right now, I'll figure it out later.

First you have to install your rock; then you run `luarocks pack mypkg` and it drops a `.rock` file in your current directory. You can upload this with `luarocks upload mypkg.all.rock`
