### ISSUE TITLE
Server disconnect

### ISSUE THREAD

**Issue by daurnimator** [legospacy/lua-irc-engine#7]
It would be nice to have a method to call when the socket has been closed; or the server shuts down.
Maybe just invent a special value for it?
e.g. `self:handle(irce.DISCONNECT)`

**Comment by legospacy** [comment]
As in, for the host application to call? You can already just implement this in the application (eg. call `irc:handle("DISCONNECT")` when the socket is closed). Or am I misunderstanding?

**Comment by daurnimator** [comment]
> As in, for the host application to call?

Yes.

> You can already just implement this in the application (eg. call irc:handle("DISCONNECT") when the socket is closed)

Yes, that was my suggestion (though to use a special unique value instead of the string `"DISCONNECT"`, which may come from a server).

--------------------

Why this might be needed:

  - Async processes/timers may need to be cancelled
  - Various plugins may need to clean up (e.g. if you have a partial MOTD).
  - Easy way to do reconnects

**Comment by legospacy** [comment]
Haven't tested this much, but it should work alright. If it doesn't, let me know.
